load("@zen//bazel:test.bzl", "zen_cc_test")

zen_cc_test(
  name="executor",
  srcs=["executor.cpp"],
  deps=["//:executor"]
)

zen_cc_test(
  name="meta",
  srcs=["meta.cpp"],
  deps=["//:meta"]
)

zen_cc_test(
  name="zen",
  srcs=["zen.cpp"],
  deps=["//:zen"]
)