repos:
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(c|cc|cxx|cpp|h|hpp|hxx|ipp)$
        args: [--style=file]