cc_binary(
  name="sequence_multi_threaded",
  srcs=["sequence_multi_threaded.cpp"],
  deps=["//:zen"]
)

cc_binary(
  name="sequence_with_all_any",
  srcs=["sequence_with_all_any.cpp"],
  deps=["//:zen"]
)

cc_binary(
  name="simple_sequence",
  srcs=["simple_sequence.cpp"],
  deps=["//:zen"]
)
